### ISSUE TITLE
Publish Release to npm

### ISSUE THREAD

**Issue by DennisOstertag** [emartech/react-native-emarsys-sdk#11]
Hello,

we would like to use this react-native wrapper, but as it is not published yet, we can't find the package on npm.
Are you planning on publishing a release soon?

We would use [this ](https://github.com/LeCiseau/react-native-emarsys)wrapper for the emarsys sdk in the meantime.

Thanks a lot!
Greetings
Dennis

**Comment by AlexeyVlasenko** [comment]
Hi!

You can install this wrapper directly from git+ssh://git@github.com/emartech/react-native-emarsys-sdk.git

**Comment by T-L-P** [comment]
Hey,
I also need to use it, but when i install it like:
`yarn add git+ssh://git@github.com/emartech/react-native-emarsys-sdk.git`
I get permission error:
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Any help appreciated

**Comment by AlexeyVlasenko** [comment]
> Hey,
> I also need to use it, but when i install it like:
> `yarn add git+ssh://git@github.com/emartech/react-native-emarsys-sdk.git`
> I get permission error:
> Output:
> [git@github.com](mailto:git@github.com): Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Any help appreciated




hello, try to install via https then

**Comment by T-L-P** [comment]
Ups, https worked, thanx!
`yarn add https://github.com/emartech/react-native-emarsys-sdk.git`

**Comment by kitingChris** [comment]
The initial question if you planning on publishing a release soon is still unanswered...

**Comment by AlexeyVlasenko** [comment]
> The initial question if you planning on publishing a release soon is still unanswered...

Seems like they are not interested on making his product better :)
I have PR dated October 23 2020 which will fix issue with autolinking, and it still not answered.
They just update readme how to use manual linking through Podfile 🤡

**Comment by biancalui-emarsys** [comment]
Hi @kitingChris , sorry that I missed the original question.
We have planned to publish the wrapper to npm, but no specific timeline for now due to other priorities and resources.
I will reopen this issue.
Thanks.

**Comment by bynite** [comment]
Hi, we are also interested in an official public release.
Please keep us updated!

Regards, Nicholas
_SportScheck GmbH_

**Comment by kadikraman** [comment]
+1 for releasing this on `npm` - it's the standard for JavaScript libraries. Installing this directly from GitHub is highly unusual.

Also just a  note, but if installing with https, it's best to install from a tag, else you'll just get the latest master branch, whatever it may be, i.e:

```sh
yarn add react-native-emarsys-wrapper@https://github.com/emartech/react-native-emarsys-sdk/archive/refs/tags/1.4.0.tar.gz
```

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
