### ISSUE TITLE
Production build fails due to last updates in this lib

### ISSUE THREAD

**Issue by DennisOstertag** [emartech/react-native-emarsys-sdk#18]
As there are no offical releases we have to pull from master and now our production app wont build anymore.

We had the SDK running for about 2 months now, as we wanted to update our production app we got errors on our build machine.
The lines that threw the error were  not even present on my development machine and i could still build there.
As i reinstalled the node modules and pods i had the same error there.
Note: we did not change anything regarding config for the Emarsys Wrapper

```
/app/ios/Pods/RNEmarsysWrapper/ios/RNEmarsysWrapper.m:578:48: error: no known instance method for selector 'sdkVersion'
        NSString *sdkVersion = [Emarsys.config sdkVersion];
                                               ^~~~~~~~~~
/app/ios/Pods/RNEmarsysWrapper/ios/RNEmarsysWrapper.m:588:43: error: no known instance method for selector 'pushToken'
        NSData *pushToken = [Emarsys.push pushToken];
                                          ^~~~~~~~~
6 warnings and 2 errors generated.
```
Do you have and idea or fixes for the errors above?

Thanks a lot

**Comment by eduzatoni** [comment]
Hi @DennisOstertag,

Could you please create a support ticket in the Emarsys help portal? We'll have a look at this.

Thank you!

**Comment by DennisOstertag** [comment]
After detailed investigation i found out the error was caused by a version mismatch. The RNEmarsysWrapper.podspec in node_modules was not updated correctly and somehow had still the dependency to 2.9.1.
I made sure to update correctly but as there were still problems, i created a patch for the file that sets the dependency to 2.14.0.

Steps to fix:
1. Make sure you updated your repo correctly
    Or check if your app did this by itself as the reference in package.json is set to latest master
2. If 1. did not fix it, check the version in your node_modules/react-native-emarsys-wrapper/ios/RNEmarsysWrapper.podspec, it should point to 2.14.0
3. Add [react-native-patch-package](https://github.com/ds300/patch-package)
4. Add following patch to your patch folder

```
diff --git a/node_modules/react-native-emarsys-wrapper/ios/RNEmarsysWrapper.podspec b/node_modules/react-native-emarsys-wrapper/ios/RNEmarsysWrapper.podspec
index 708397e..0512f05 100644
--- a/node_modules/react-native-emarsys-wrapper/ios/RNEmarsysWrapper.podspec
+++ b/node_modules/react-native-emarsys-wrapper/ios/RNEmarsysWrapper.podspec
@@ -18,6 +18,6 @@ Pod::Spec.new do |s|
 	s.source_files  = "ios/*.{h,m}"
 	s.requires_arc  = true
 	s.dependency "React", ">= 0.60.0"
-	s.dependency "EmarsysSDK", "~> 2.9.1"
+	s.dependency "EmarsysSDK", "~> 2.14.0"
 
 end

```
