### ISSUE TITLE
Event Handling import missing

### ISSUE THREAD

**Issue by bynite** [emartech/react-native-emarsys-sdk#19]
Hi there,
good work so far, thanks for that.

When implementing **Event handling**, code for iOS and Android says using `RNEmarsysEventHandler`, but I am probably missing `import`s for both.

```
from file: AppDelegate.m

  RNEmarsysEventHandler *rnEMSEventHandler = [RNEmarsysEventHandler allocWithZone: nil];
  ^~~~~~~ Use of undeclared identifier 'RNEmarsysEventHandler'
    Emarsys.inApp.eventHandler = rnEMSEventHandler;
    Emarsys.notificationCenterDelegate.eventHandler = rnEMSEventHandler;
    UNUserNotificationCenter.currentNotificationCenter.delegate = Emarsys.notificationCenterDelegate;
```

Can you please tell me or/and update the Wiki part accordingly what the correct import code is. Thanks in advance!

**Comment by biancalui-emarsys** [comment]
Hi @bynite ,
Sorry for the late reply. You will need to import RNEmarsysEventHandler.
`#import <RNEmarsysWrapper/RNEmarsysEventHandler.h>`
`import com.emarsys.rnwrapper.RNEmarsysEventHandler;`
