### ISSUE TITLE
Error in RNEmarsysWrapper.m

### ISSUE THREAD

**Issue by PavelMartynovN** [emartech/react-native-emarsys-sdk#2]
In RNEmarsysWrapper.m on line 766 i get an error "Too many arguments provided to function-like macro invocation"
![Снимок экрана 2020-05-29 в 13 04 55](https://user-images.githubusercontent.com/24667598/83248202-5d014580-a1ad-11ea-97ca-dc823aebcb25.png)

I fixed this like this:
![Снимок экрана 2020-05-29 в 13 03 25](https://user-images.githubusercontent.com/24667598/83248231-6be7f800-a1ad-11ea-98f0-474445e4c0d0.png)

Please fix this error in the library.

**Comment by eduzatoni** [comment]
Hi Pavel,

Thank you for your suggestion. It has been fixed in my last commit.

Please, let me know if there's anything else we could do to help your implementation.

Best,
Eduardo
