### ISSUE TITLE
Can't download library

### ISSUE THREAD

**Issue by LukaZagar1995** [emartech/react-native-emarsys-sdk#27]
I have trouble downloading the library. I tried example a week ago and it worked, but today I can't download the library. With yarn I have  
```
Can't add "react-native-emarsys-wrapper": invalid package version "1.2".
```
and with npm install 
```
verbose stack Error: premature close
10 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
10 verbose stack     at PassThrough.emit (events.js:327:22)
10 verbose stack     at emitCloseNT (internal/streams/destroy.js:81:10)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
```
Anyone has similar problem?

**Comment by biancalui-emarsys** [comment]
Hi @LukaZagar1995 , 
I'm sorry we used the wrong version. The correct version is 1.2.0 . It is updated.
May you try again installing the package? Thanks.
`npm install git+ssh://git@github.com/biancalui-emarsys/react-native-emarsys-sdk.git#1.2.0 --save`

**Comment by LukaZagar1995** [comment]
It is all working now. Thanks 😄
