### ISSUE TITLE
[BUG] Changing application code not working on Android 

### ISSUE THREAD

**Issue by TimP4w** [emartech/react-native-emarsys-sdk#31]
`await Emarsys.changeApplicationCode('****', ****);`
 
 is not working as expected on android.
 Let's assume we have 2 app codes. Changing app code on android does not listen to the new one, but keep getting notifications from the old.
 
 Example: 
 
 Setup in the MainApplication.java onCreate() method with
 ```
 EmarsysConfig config = new EmarsysConfig.Builder()
    .application(this)
    .mobileEngageApplicationCode("app-code-1")
    .contactFieldId(contact-identifier-id) 
    .build();
 ```
 
 Push are received correctly.
 
 ```
   const appCode = await Emarsys.getApplicationCode();
   // Output: "app-code-1"
 ```
 
 Then call:
 ```
  await Emarsys.changeApplicationCode("app-code-2", contact-identifier-id);
  const appCode = await Emarsys.getApplicationCode();
  // Output: "app-code-2" 
  ```
  
  Expected behaviour:
  Pushes are received if sent to app-code-2.
  
  Actual behaviour: 
  Pushes are NOT received if sent on app-code-2, but are received if sent to app-code-1.
  
  ~~This bug is NOT present on iOS.~~
  
  Calling `await Emarsys.clearContact();` before changing the code and resetting it later does not solve this issue either.
 
 This behaviour is quite critical for our app.
 
EDIT:
After some more investigation I've discovered that the problem is not related to changing it via the provided method, but even rebuilding the app with the new code does not correctly listen for the notification sent to the correct id, but it's still bound to the previous one. I believe the problem here is that your SDK does not correctly notify your backend to change the user to the correct app (on Android). ~~This works pretty well on iOS.~~

EDIT 2: It didn't actually work well on iOS. After rebuilding the app and some more tests, I noticed that it wasn't changing correctly as well.

**Comment by eduzatoni** [comment]
Hi @TimP4w,

Can I know which wrapper version you have used?

Could you please create a support ticket in the Emarsys help portal? There we would have access to your account and logs which would help us to troubleshoot it.

Thanks!
Edu

**Comment by TimP4w** [comment]
@eduzatoni I'm using version 1.3.0

    "react-native-emarsys-wrapper": "git+ssh://git@github.com/emartech/react-native-emarsys-sdk.git#1.3.0"
    
Sadly my login is not valid for the help portal. Is there any other way to reach you?

**Comment by eduzatoni** [comment]
Hi @TimP4w,

Can I know your account name? I can contact your implementation consultant or customer success manager.

**Comment by TimP4w** [comment]
@eduzatoni I'm not at liberty to share the account name, but the id is 761900574

**Comment by TimP4w** [comment]
Now I managed to make it work "reliably" on android, but not on iOS.

This is what I'm doing:

```
const emarsysAppCode = getCode(-- my logic --);  // "app-code-1"
const emarsysOtherCode = getCode(-- my logic --); // "app-code-2"

// Clear other app
 await Emarsys.changeApplicationCode(emarsysOtherCode, "contact-identifier-id");
 await Emarsys.setContact(contact);
 await Emarsys.push.clearPushToken();
 await Emarsys.clearContact();
 
 // Set correct app
await Emarsys.changeApplicationCode(emarsysAppCode,  "contact-identifier-id");
await Emarsys.push.setPushToken(token); // I'm getting the token via another library which seems to be more reliable than "Emarsys.push.pushToken")
const appCode = await Emarsys.getApplicationCode(); // if this is not called, it does not work for some reason
await Emarsys.setContact(contact);
console.log('Emarsys App code: ' + appCode); // Output  "app-code-2"
```

This work on Android but not on iOS, or rather, it works with the first app code, but it stops working when I change it.

If I check the latest users on the Emarsys dashboard for both apps, the "Push Token" tick is set correctly for both iOS and Android, but only Android receives the pushes.

The whole process of logging in the not desired app to clear the push token is quite cumbersome and error prone, but without doing it the devices will get the notification from both app codes (or just one, but usually the wrong one, this also seems to be quite random)
