### ISSUE TITLE
Notifications events doesn't work on Android from 1.3.0

### ISSUE THREAD

**Issue by LukaZagar1995** [emartech/react-native-emarsys-sdk#33]
When I am sending notifications, with the 1.3.0 version, with some action the payload and the event doesn't get passed to JS part. As far as I can see nothing has changed in the this library so I am guessing that the problem is with 2.16 emarsys SDK. I have downgraded react native wrapper to 1.2.0 version and events are working normally there.

**Comment by DennisOstertag** [comment]
Hello there,

we have the same issue.
Rich push notifications on iOS are working fine and the deep links we put on the buttons are getting triggered. The same thing was working fine on Android, but for now Android wont receive the events.

On the SDK Events we can see that the push notification click event was recognized but on android nothing more happens, on iOS we can see the events found for that actions.

**Comment by eduzatoni** [comment]
Hi all,

We're aware of the issue and we're working with the SDK team to solve it.

I keep you posted.

Best,
Edu

**Comment by eduzatoni** [comment]
Hi all,

It was a problem in the native SDK. The fix is included in the latest release.
