### ISSUE TITLE
Error java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;

### ISSUE THREAD

**Issue by nmsdvid** [emartech/react-native-emarsys-sdk#44]
Hello. I'm getting this error: `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId; ` when i'm adding `implementation 'com.emarsys:emarsys-firebase:+' ` into `build.gradle` any ideas?

**Comment by Alberto-Hernandezg** [comment]
Hello @nmsdvid 
The "+" identificator seems to cause some problems, which I was able to reproduce. Try specifying the concrete version:     `implementation "com.emarsys:emarsys-firebase:3.0.1"`.

**Comment by octavianvoloaca-tremend** [comment]
Hello,

I think is impacting with other libraries which requires FirebaseInstanceId. Maybe you are using other services from firebase (react-native-firebase) and you should update those libraries also

**Comment by Alberto-Hernandezg** [comment]
Hello @nmsdvid
The "+" identificator seems that could cause some problems. Try specifying the concrete version: implementation "com.emarsys:emarsys-firebase:3.0.1". In case none of this works, you could share your gradle file so we can have a look.
Thanks!

**Comment by nmsdvid** [comment]
The issue was solved by updating my react-native-firebase dependencies.
