### ISSUE TITLE
iOS Push Notifications in foreground not working

### ISSUE THREAD

**Issue by octavianvoloaca-tremend** [emartech/react-native-emarsys-sdk#45]
Push notifications while app is closed or in background are working but not while the app is in foreground. We need to make extra configurations for that?

**Comment by eduzatoni** [comment]
You need to set Emarsys push as delegate after the SDK set up in your `AppDelegate`
https://github.com/emartech/react-native-emarsys-sdk/wiki#ios-1
```objective-c
UNUserNotificationCenter.currentNotificationCenter.delegate = [Emarsys push];
```

**Comment by octavianvoloaca-tremend** [comment]
oh :)). yeap, it seems that the order of the operations have an impact. Thank you!
