### ISSUE TITLE
setEventHandler delay on Android

### ISSUE THREAD

**Issue by bynite** [emartech/react-native-emarsys-sdk#49]
Hi there,

on Android there is quite a delay from App Launch to the Emarsys push notification event.
Because of that, I have two questions:
1. Is it somehow possible to reduce that time gap?
2. If not, is there any way to detect, that the app launch was triggered by the push notification, so that we could maybe show a loading icon until the Emarsys event kicks in?

Thanks in advance!
(SportScheck)

**Comment by eduzatoni** [comment]
Hi @bynite,

Sorry for the delayed reply.

Please, create a ticket in the Emarsys help portal. 

Best,
Eduardo
