### ISSUE TITLE
No visible @interface for 'CLLocationManager' declares the selector 'authorizationStatus'

### ISSUE THREAD

**Issue by PavelMartynovN** [emartech/react-native-emarsys-sdk#5]
I got an error at EmarsysSDK/EMSGeofenceInternal.m
![Снимок экрана 2020-10-02 в 14 16 27](https://user-images.githubusercontent.com/24667598/94917781-e1483a00-04b9-11eb-89cc-35c135d4ebfa.png)
Could you please check this error. Thanks in advance.
Podfile:
![Снимок экрана 2020-10-05 в 12 26 34](https://user-images.githubusercontent.com/24667598/95063250-cae2ee00-0706-11eb-86bc-ce8931d21b0c.png)
package.json:
![Снимок экрана 2020-10-05 в 12 26 17](https://user-images.githubusercontent.com/24667598/95063287-d504ec80-0706-11eb-8ed4-3ccd3bf64a82.png)

**Comment by gayanhewa** [comment]
Any update on this?

**Comment by eduzatoni** [comment]
Hi @gayanhewa and @PavelMartynovN,

Sorry for the delayed reply here.

The instance property `authorizationStatus` is only available in the iOS 14 framework. You should update Xcode to version 12 or above.

Please, next time create a ticket through the Emarsys help portal.

Thank you!
