### ISSUE TITLE
app:checkDebugAarMetadata

### ISSUE THREAD

**Issue by Malintan2112** [emartech/react-native-emarsys-sdk#57]
Execution optimizations have been disabled for task ':app:processDebugMainManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/admin/Documents/KLG Project/upgradeVersionReactNative/ruparupamobileappsUpgradeVersion/android/app/build/intermediates/navigation_json/debug/navigation.json'. Reason: Task ':app:processDebugMainManifest' uses this output of task ':app:copyDebugIconFonts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
