### ISSUE TITLE
Mysterious Error on trackCustomEvent

### ISSUE THREAD

**Issue by sbycrosz** [emartech/react-native-emarsys-sdk#61]
Hi, 

We noticed that trackCustomEvent has been throwing numerous errors with unclear error message 

![Screen Shot 2022-05-12 at 2 19 24 PM](https://user-images.githubusercontent.com/4867178/168004807-c58e4d83-c172-4ead-8381-c343e469b2cf.png)

![Screen Shot 2022-05-11 at 5 36 32 PM](https://user-images.githubusercontent.com/4867178/167818992-6f1b4ba7-c3c9-41ff-8cca-2a1259030a7d.png)

Our latest changes involves adding `com.google.android.gms.permission.AD_ID` permission and bumping targetSDK to 31 as defined [here](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en). 

Has anyone encountered similar problems?

-S

Edit: 

Upon some investigation, we found that Emarsys is getting 400 errors from the server

```
ResponseErrorException{statusCode=400, statusMessage='Bad Request', body='{  "reason" : "Missing Header: x-contact-token"}'}
```

We're going to try upgrading RNEmarsysWrapper from 1.3.0 to the 1.5.0 and see if the problem dissapears

**Comment by robwalkerco** [comment]
I've encountered random errors from all the Emarsys methods.
I've resorted to wrapping each method call in the try/catch to protect the app from crashes caused by Emarsys.

**Comment by bonesyblue** [comment]
Hi all 👋 

I have also encountered a similar issue with the `trackCustomEvent` method. Debugging with Xcode and an iOS device I discovered that I can reproduce the issue consistently by disabling the Wi-Fi connection on my test device (Note: this device has no mobile network connection)

I set a couple of breakpoints in the following positions:

<img width="720" alt="Screenshot 2022-10-21 at 11 38 16" src="https://user-images.githubusercontent.com/7486722/197165233-512a10bb-373c-4298-a8f2-ea597a8a9236.png">

When the device loses connection with Wi-Fi, the Emarsys custom events are batched locally and once the Wi-Fi connection resumes, the batched custom event requests are then sent. However, every custom event fails with the following error:

```
2022-10-21 11:24:09.861032+0200 APP[6093:517998] EmarsysSDK - 🔵 - log_status 
 Data: 
 status: {
    error = "A server with the specified hostname could not be found.";
} 
className: EMSRESTClient 
methodName: executeWithRequestModel:coreCompletionProxy: 
parameters: {
  ...
}
```

The error received in the JS domain does not contain this information unfortunately. Also, with a stable Wi-Fi connection the custom events are successfully reported.

For now, I have stopped reporting errors thrown by the `trackCustomEvent`, however, it would be great if this faulty offline behaviour could be investigated further as it means that a large amount of custom event data is not being reported :) 

### Environment information

**react-native-emarsys-sdk: v1.4.0** 
**EmarsysSDK: v3.0.0**

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
