### ISSUE TITLE
iOS bridging error on newer react native versions

### ISSUE THREAD

**Issue by DennisOstertag** [emartech/react-native-emarsys-sdk#65]
Hello there,

we currently get an error during build after pod install.
   
```
In file included from /Users/.../app/ios/Pods/RNEmarsysWrapper/ios/RNEmarsysEventHandler.m:6:
/Users/.../app/ios/Pods/RNEmarsysWrapper/ios/RNEmarsysWrapper.h:11:48: error: cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?
@interface RNEmarsysWrapper : RCTEventEmitter <RCTBridgeModule>
                                               ^~~~~~~~~~~~~~~
                                               RCTBridgeMethod
In file included from /Users/.../app/ios/Pods/RNEmarsysWrapper/ios/RNEmarsysEventHandler.m:6:
In file included from /Users/.../app/ios/Pods/RNEmarsysWrapper/ios/RNEmarsysWrapper.h:3:
/Users/.../app/ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h:13:11: note: 'RCTBridgeMethod' declared here
@protocol RCTBridgeMethod;

```

We added expo libs recently and are using react native 0.64.2.
By now we fixed it, by changing the file in the podfile post_install.

The file that needs to be changed is [RNEmarsysWrapper.h](https://github.com/emartech/react-native-emarsys-sdk/blob/master/ios/RNEmarsysWrapper.h) 
Sadly it was not changed in version 1.6

I will submit a support ticket too.

But as others might run into the same issue, i will repopen this issue here.

Greetings
Dennis

I already submitted this issue, but it got closed without being fixed.
[iOS bridging error on newer react native versions](https://github.com/emartech/react-native-emarsys-sdk/issues/51)

**Comment by kevin-madden-gf** [comment]
@DennisOstertag hello, we seem to be experiencing the same error.  can you clarify what you needed to add in post_install to be able to resolve your issue?  Thanks for any help!

**Comment by DennisOstertag** [comment]
Thats what i put in the post install of my podfile.
Hope it helps, even tho it is quite a late reply
```
# Change Emarsys Wrapper React Bridge
  replace_text = 'RCTBridgeMethod'

  # search the Pods for Emarsys folder
  directory = installer.config.project_pods_root + 'RNEmarsysWrapper/ios/'
  Dir.foreach(directory) do |path|
    full_path = directory + path
    if File.directory?(full_path) 
      emarsys_wrapper_file = full_path + 'RNEmarsysWrapper.h'
      # check if RNEmarsysWrapper header file exists
      if File.exist?(emarsys_wrapper_file)
        # read the file
        text = File.read(emarsys_wrapper_file)
        # delete the file, as the permissions dont allow us to open the file otherwise
        File.delete(emarsys_wrapper_file)
        # replace wrong code
        new_contents = text.gsub('RCTBridgeModule', replace_text)
        # recreate the file with default rights and the correct content
        File.open(emarsys_wrapper_file, "w") {|file| file.puts new_contents }
        puts "Content of RNEmarsysWrapper.h fixed"
        puts "Pod post_install done"
      end
    end
  end
```

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
