### ISSUE TITLE
APK size got increased almost double after upgrading to 1.7.0

### ISSUE THREAD

**Issue by Malintan2112** [emartech/react-native-emarsys-sdk#67]
my react native 68.2 app APK size got increased almost double after upgrading to 1.7.0

**Comment by emilioheinz** [comment]
Same here

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
