### ISSUE TITLE
iOS autolink module is Null

### ISSUE THREAD

**Issue by AlexeyVlasenko** [emartech/react-native-emarsys-sdk#7]
I'm using RN autolink feature.
As i can see, EmarsysSDK and RNEmarsysWrapper has installed during pod process. But, unfortunately, i can't find libRNEmarsysWrapper.a inside Pod's products folder, so i can't use native module, because its null

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
