### ISSUE TITLE
Turn on Issues for Flutter Emarsys SDK on GitHub

### ISSUE THREAD

**Issue by yura2000** [emartech/react-native-emarsys-sdk#76]
Hi Emarsys!
I having an issue with flutter Emarsys SDK. Please, turn on "Issues" in git repo.

I'm trying to integrate the SDK into a Flutter project for push notifications. I receive a push on both platforms, but when I press on it, the event handler works only for Android. In iOS log I got this message:
EmarsysSDK - 🔵 - log_status
 Data:
 status: {
    error = "The data couldn\U2019t be read because it isn\U2019t in the correct format.";
}
className: EMSStorage
methodName: dictionaryForKey:
parameters: {
    key = "DEVICE_EVENT_STATE_KEY";
}

**Comment by eduzatoni** [comment]
Hi,

Sorry for the late reply. The right process is to open a ticket in Emarsys’ official support system so we can keep track of it. Please create a ticket in the help portal if it's still an issue.

Thank you,
Edu
